### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Ghost1311** [Bryan-0/AylBot-League-of-Legends#1]
How can I fix this problem?
![image](https://user-images.githubusercontent.com/94529415/185985902-0c743269-e804-4ab1-ae62-d9dbb5583579.png)

**Comment by Bryan-0** [comment]
Hey @Ghost1311, sorry for the late response. 

Have you tried using `pip install requests`? If that doesn't work try using `python -m pip install requests`.

I recommend you to upgrade your python version to at least 3.5+.
